@host = http://localhost:8080

### [IP] Req — Envie 6x seguidas (bloqueia na 6ª)
GET {{host}}/
Accept: application/json

###

### [TOKEN] Req — Envie 11x seguidas (bloqueia na 11ª)
GET {{host}}/
API_KEY: token-secreto-123
Accept: application/json

###

### [OURO] Com IP bloqueado, Token ainda passa (200)
GET {{host}}/
API_KEY: outro-token-vip
Accept: application/json

###

### [PING] Health check
GET {{host}}/ping
Accept: application/json

###
